version: '2'

services:
  gitlab:
    image: gitlab/gitlab-ce:12.10.11-ce.0
    container_name: gitlab
    restart: unless-stopped
    hostname: gitlab.nu12.xyz
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    ports:
        - 80:80
        - 443:443
      
volumes:
  gitlab_config:
    external: true
  gitlab_logs:
    external: true
  gitlab_data:
    external: true