version: '2'

services:
  gitlab:
    image: gitlab/gitlab-ce:13.0.3-ce.0
    container_name: gitlab
    restart: unless-stopped
    hostname: gitlab.example.com
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
        nginx['redirect_http_to_https'] = true
        nginx['ssl_certificate'] = "/etc/gitlab/ssl/my_cert.crt"
        nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/my_cert.key"
        nginx['http2_enabled'] = false
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
      - /etc/ssl/certs:/etc/gitlab/ssl

  nginx:
    image: nginx:1.17.10
    container_name: nginx
    restart: unless-stopped 
    volumes: 
      - ./conf.d:/etc/nginx/conf.d:ro
      - /etc/ssl/certs:/certs:ro
    ports:
        - 80:80
        - 443:443
      
volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data: